### ISSUE TITLE
Crash on expo build

### ISSUE THREAD

**Issue by AChevallier** [glassfy/react-native-glassfy-module#1]
Hello,
I've got a problem when I build my app with eas.

My version `"react-native-glassfy-module": "^1.3.2",`

My error : 
```
[!] CocoaPods could not find compatible versions for pod "GlassfyGlue":
[INSTALL_PODS]   In Podfile:
[INSTALL_PODS]     react-native-glassfy-module (from `../../../node_modules/react-native-glassfy-module`) was resolved to 1.3.2, which depends on
[INSTALL_PODS]       GlassfyGlue (= 1.3.1)
[INSTALL_PODS] 
[INSTALL_PODS] None of your spec sources contain a spec satisfying the dependency: `GlassfyGlue (= 1.3.1)`.
[INSTALL_PODS] 
[INSTALL_PODS] You have either:
[INSTALL_PODS]  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
[INSTALL_PODS]  * mistyped the name or version.
[INSTALL_PODS]  * not added the source repo that hosts the Podspec to your Podfile.
[INSTALL_PODS] 
```

Can you help me ?!

Thank you very much

**Comment by marcopifferi** [comment]
Could you please try do update your cocoa pods repository using the following command 
`pod repo update`

**Comment by AChevallier** [comment]
I am using EAS (https://expo.dev/eas) so i cannot use pod command, EAS do that by itself.
I already tried to clear to EAS cache and it didn't work.

I remember I tried your lib in may or june and it was working.

**Comment by marcopifferi** [comment]
They must have changed something on eas build because we have not changed the reference to GlassfyGlue cocoa pods ( it is in this module since the beginning) and the module always build fine with EAS.

we will investigate why EAS is not downloading the latest Cocoapods repository and locate the library

**Comment by AChevallier** [comment]
@marcopifferi Thank you

Can I do something to help ?

**Comment by marcopifferi** [comment]
We are actually investigating. It is not clear why expo is not using the latest cocapods repository. Let me know if you discover something

**Comment by marcopifferi** [comment]
The problem does not appear on a brand new project: it seems related to something cached on Expo.

Could you try to specify a different cache key in your build profile?
https://docs.expo.dev/build-reference/eas-json/#cache

**Comment by AChevallier** [comment]
The problem seems to be fixed ! 
Thanks !
