### ISSUE TITLE
Android - Subscription Always returns as Owned after initial purchase

### ISSUE THREAD

**Issue by liyamahendra** [glassfy/react-native-glassfy-module#11]
I have integrated this module in my react native app. The purchase of subscription works fine.

The call to `await Glassfy.restorePurchases();` returns the below response:

```
{"all": [{"accountableSkus": [Array], "entitlement": -5, "expireDate": 1699872931, "isValid": false, "permissionId": "pmp_permissions"}, {"accountableSkus": [Array], "entitlement": -5, "expireDate": 1699872931, "isValid": false, "permissionId": "permissions"}], "subscriberId": "7de8695b6ed64753abd75ab6c956d61c"}
```

As seen, the permission is not valid. When I try to buy the subscription again, it gives the below error:

```{"nativeStackAndroid":[],"userInfo":null,"message":"GlassfyError(code=ProductAlreadyOwned, description=Product already owned, debug=Failure to purchase since item is already owned (ITEM_ALREADY_OWNED))","code":"GlassfyError(code=ProductAlreadyOwned, description=Product already owned, debug=Failure to purchase since item is already owned (ITEM_ALREADY_OWNED))"}```

I'm using `1.5.3`

Please advise.

**Comment by marcopifferi** [comment]
Could you please contact as using the intercom bubble on our website? We would like to access the exact account to check it out and we need some of yours personal details.
