### ISSUE TITLE
Missing `transactionId` in type `GlassfyTransaction` returned from `Glassfy.purchaseSku(sku)`

### ISSUE THREAD

**Issue by benjamin-beau** [glassfy/react-native-glassfy-module#15]
Hi,

Could you make the `transactionId` property available in type `GlassfyTransaction` returned by the purchase function `Glassfy.purchaseSku(sku)`. 

We need to be able to have a validation process between our front and back end. The id will be sent to our backend when unlocking feature x. Then the backend can verify if the transaction exists in the `original_transaction_id` property of the `/subscriber` API endpoint return object. This allows us to prevent users to unlock features by simply calling an endpoint without a third party validation from our backend. The `transactionId` will be associated to the feature unlock in our business logic.

Thank you.

**Comment by marcopifferi** [comment]
Sorry at the moment we are not are not planning to support this type of backend verification .
Please have a look at glassfy webhooks to implement backend processing of the transaction.
