### ISSUE TITLE
Billing Library version 6

### ISSUE THREAD

**Issue by EightPool** [glassfy/react-native-glassfy-module#16]
Hello, I have received a warning from Google regarding the deprecation of older versions of the Google Play Billing Library after August 31, 2024.

Are there any plans to upgrade this module to Google Play Billing Library 6?

![Screenshot 2024-06-01 at 5 12 57 pm](https://github.com/glassfy/react-native-glassfy-module/assets/46991020/e22d3dbd-a792-4cb5-bae7-da3f541734f8)

**Comment by drodimin** [comment]
I am also concerned about this. The deadline is approaching.

**Comment by liyamahendra** [comment]
@marcopifferi any updates on this please?
