### ISSUE TITLE
How to use `GlassfyError` to pull the description for the error?

### ISSUE THREAD

**Issue by liyamahendra** [glassfy/react-native-glassfy-module#7]
I'm using the React native module for Glassfy with TypeScript.

While testing, I received an error as below:
```
{
	"nativeStackAndroid": [],
	"userInfo": null,
	"message": "GlassfyError(code=SDKNotInitialized, description=SDK not initialized, debug=null)",
	"code": "GlassfyError(code=SDKNotInitialized, description=SDK not initialized, debug=null)"
}
```

I tried to type cast the error as `GlassfyError` but couldn't find one.

Please advise.

**Comment by marcopifferi** [comment]
We will improve the error support in a future version of the SDK
