### ISSUE TITLE
No retrocompatibility with older React Native version

### ISSUE THREAD

**Issue by sofianegargouri** [glassfy/react-native-glassfy-module#8]
Hi folks,

I've been trying to integrate this SDK to an existing React Native app.

Because of the following line: https://github.com/glassfy/react-native-glassfy-module/blob/main/android/build.gradle#L130C39-L131C48

We are unable to build because of the following error: `Duplicate class com.facebook.yoga.YogaWrap found in modules jetified-react-android-0.71-debug.4-debug-runtime (com.facebook.react:react-android:0.71.4) and jetified-react-native-0.67.4-runtime (com.facebook.react:react-native:0.67.4)`

**Comment by marcopifferi** [comment]
Sorry at the moment we do not support old react native versions.
